// ============================================================
// Handsup — Events Service
// Festival/event API calls
// ============================================================

import { supabase } from './supabase';
import { Event } from '../types';

// Get all events
export async function getEvents(filter?: {
  upcoming?: boolean;
  country?: string;
  partner?: boolean;
}): Promise<Event[]> {
  let query = supabase
    .from('events')
    .select('*')
    .order('start_date', { ascending: true });

  if (filter?.upcoming) {
    query = query.eq('is_upcoming', true);
  }

  if (filter?.country) {
    query = query.eq('country', filter.country);
  }

  if (filter?.partner) {
    query = query.eq('is_partner', true);
  }

  const { data, error } = await query;
  if (error) throw error;
  return data ?? [];
}

// Get single event by slug
export async function getEvent(slug: string): Promise<Event | null> {
  const { data, error } = await supabase
    .from('events')
    .select('*')
    .eq('slug', slug)
    .single();

  if (error) return null;
  return data;
}

// Create a new event
export async function createEvent(event: {
  name: string;
  slug: string;
  location: string;
  city: string;
  country: string;
  start_date: string;
  end_date?: string;
  description?: string;
  genre_tags?: string[];
  website_url?: string;
  is_private?: boolean;
  /**
   * Invite code for private events. Should be a 6-char uppercase alphanumeric
   * string generated by the caller (e.g. AddEventScreen via generateInviteCode()).
   * If not provided for a private event, a fallback is generated server-side.
   */
  invite_code?: string;
}): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser();
  // Use caller-supplied invite_code if provided; otherwise generate a fallback
  const inviteCode = event.invite_code
    ?? (event.is_private ? Math.random().toString(36).substring(2, 8).toUpperCase() : null);
  const { error } = await supabase.from('events').insert({
    ...event,
    created_by: user?.id,
    invite_code: inviteCode,
  });
  if (error) throw error;
}

export async function joinPrivateEvent(inviteCode: string): Promise<void> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error('Not authenticated');
  const { data: event } = await supabase.from('events').select('id').eq('invite_code', inviteCode).single();
  if (!event) throw new Error('Invalid invite code');
  const { error } = await supabase.from('event_members').upsert({ event_id: event.id, user_id: user.id });
  if (error) throw error;
}

export async function getMyEventMemberships(): Promise<string[]> {
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return [];
  const { data } = await supabase.from('event_members').select('event_id').eq('user_id', user.id);
  return data?.map((m: any) => m.event_id) ?? [];
}

export async function getEventMemberCount(eventId: string): Promise<number> {
  const { count } = await supabase
    .from('event_members')
    .select('*', { count: 'exact', head: true })
    .eq('event_id', eventId);
  return count ?? 0;
}

// Get upcoming events in a specific city (next 30 days)
export async function getUpcomingEventsByCity(city: string, limit = 5): Promise<Event[]> {
  const today = new Date().toISOString().split('T')[0];
  const thirtyDaysAhead = new Date();
  thirtyDaysAhead.setDate(thirtyDaysAhead.getDate() + 30);
  const future = thirtyDaysAhead.toISOString().split('T')[0];

  const { data, error } = await supabase
    .from('events')
    .select('*')
    .gte('start_date', today)
    .lte('start_date', future)
    .ilike('city', `%${city}%`)
    .order('start_date', { ascending: true })
    .limit(limit);

  if (error) throw error;
  return data ?? [];
}

// Get upcoming events (general fallback — no city filter)
export async function getUpcomingEvents(limit = 5): Promise<Event[]> {
  const today = new Date().toISOString().split('T')[0];
  const { data, error } = await supabase
    .from('events')
    .select('*')
    .gte('start_date', today)
    .order('start_date', { ascending: true })
    .limit(limit);
  if (error) throw error;
  return data ?? [];
}

// Search events
export async function searchEvents(query: string): Promise<Event[]> {
  const { data, error } = await supabase
    .from('events')
    .select('*')
    .or(`name.ilike.%${query}%,city.ilike.%${query}%,country.ilike.%${query}%`)
    .order('start_date', { ascending: false });

  if (error) throw error;
  return data ?? [];
}
